#include "system_data.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/sysinfo.h>
#include <unistd.h>


int cpu_data() {
    // TODO: Improve this function to use more accurate cpu statistics. similar to network_data()
    FILE* file = fopen("/proc/stat", "r");
    if (file == NULL) {
        printf("Error opening /proc/stat\n");
        return -1;
    }

    char line[256];
    fgets(line, sizeof(line), file);

    char* token = strtok(line, " ");
    int user = atoi(token);
    token = strtok(NULL, " ");
    int nice = atoi(token);
    token = strtok(NULL, " ");
    int system = atoi(token);
    token = strtok(NULL, " ");
    int idle = atoi(token);

    fclose(file);

    int total = user + nice + system + idle;
    double total_cpu_usage = 100.0 - (100.0 * idle / total);

    printf("CPU Usage: %.2f%%\n", total_cpu_usage);

    return 0;
}

int memory_data(){
// TODO: Improve this function to use more accurate memory statistics. similar to network_data()
    int MemTotal = 0, MemFree = 0, Buffers = 0, Cached = 0;

    FILE* file = fopen("/proc/meminfo", "r");
    if (file == NULL) {
        printf("Error opening /proc/meminfo\n");
        return -1;
    }

    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file)) {
        if (sscanf(buffer, "MemTotal: %d kB", &MemTotal) == 1) {

        } else if (sscanf(buffer, "MemFree: %d kB", &MemFree) == 1) {

        } else if (sscanf(buffer, "Buffers: %d kB", &Buffers) == 1) {

        } else if (sscanf(buffer, "Cached: %d kB", &Cached) == 1) {

        }
    }
    fclose(file);
    
    int MemUsed = MemTotal - MemFree - Buffers - Cached;

    int MemUsedPercentage = 100 * MemUsed / MemTotal;

    printf("Memory Usage: %d%%\n", MemUsedPercentage);

    return 0;
       
}

// ! after making the other 2 funcs copilot knew exactly what I wanted to do next. Even this comment..... scary stuff.
// ! I'm not sure if I should be happy or scared. I'm happy that it's so smart but scared that it's so smart. <-this comment was also generated by copilot.
// ! anyway it got it wrong it wont copile life aint that easy.
int diskio_data(){
    // TODO: Improve this function to use more accurate disk I/O statistics. similar to network_data()
    const char* target_device = "sda";
    FILE* file = fopen("/proc/diskstats", "r");
    if (file == NULL) {
        printf("Error opening /proc/diskstats\n");
        return -1;
    }


    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file)) {
        int major, minor;
        char device[256];
        unsigned long long reads, reads_merged, sectors_read, read_time;
        unsigned long long writes, writes_merged, sectors_written, write_time;
        unsigned long long io_in_progress, io_time, io_time_weighted;


        // ? added more specifiers that it needed?? bruh.
        // gave me what I wanted but not exactly. Some work to be done but 
        // definitely a good start.
        if (sscanf(buffer, "%d %d %s %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu",
                   &major, &minor, device,
                   &reads, &reads_merged, &sectors_read, &read_time,
                   &writes, &writes_merged, &sectors_written, &write_time,
                   &io_in_progress, &io_time, &io_time_weighted) >= 14) {
            if (strcmp(device, target_device) == 0) {
                unsigned long long total_io_ms = read_time + write_time;
                double total_io_seconds = total_io_ms / 1000.0;

                printf("Total I/O Wait Time: %.3f seconds\n", total_io_seconds);

                break;
            }
        }
    }

    fclose(file);
    return 0;
}


// ! again copilot knew what I wanted to do next. It's like it's reading my mind. <-this comment was also generated by copilot.
// ! scary stuff.....

struct NetworkData {
    unsigned long long bytes_received;
    unsigned long long packets_received;
    unsigned long long bytes_transmitted;
    unsigned long long packets_transmitted;
};



int network_data(int interval){
    struct NetworkData* stats_start = malloc(sizeof(struct NetworkData)); 
    struct NetworkData* stats_end = malloc(sizeof(struct NetworkData));
    if (stats_start == NULL || stats_end == NULL) {
        perror("Error allocating memory");
        return -1;
    }

    FILE* file = fopen("/proc/net/dev", "r");
    if (file == NULL) {
        perror("Error opening /proc/net/dev");
        return -1;
    }

    memset(stats_start, 0, sizeof(struct NetworkData));
    memset(stats_end, 0, sizeof(struct NetworkData));

    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file)) {

        if (strstr(buffer, "Inter-") || strstr(buffer, " face")) {
            continue;
        }

        char interface[32];
        unsigned long long bytes_received, packets_received, bytes_transmitted, packets_transmitted;

        // ! copilot seems to struggle with the amount of specifiers needed. Usually adds more than needed.
        if (sscanf(buffer, "%s %llu %llu %llu %llu",
                   interface,
                   &bytes_received, &packets_received,
                   &bytes_transmitted, &packets_transmitted) == 5) {
                    
                    stats_start->bytes_received = bytes_received;
                    stats_start->packets_received = packets_received;
                    stats_start->bytes_transmitted = bytes_transmitted;
                    stats_start->packets_transmitted = packets_transmitted;                
                    break;
        }
        
    }

    fclose(file);

    sleep(interval);

    file = fopen("/proc/net/dev", "r");
    if (file == NULL) {
        perror("Error opening /proc/net/dev");
        return -1;
    }

    while (fgets(buffer, sizeof(buffer), file)) {

        if (strstr(buffer, "Inter-") || strstr(buffer, " face")) {
            continue;
        }

        char interface[32];
        unsigned long long bytes_received, packets_received, bytes_transmitted, packets_transmitted;

        if (sscanf(buffer, "%s %llu %llu %llu %llu",
                   interface,
                   &bytes_received, &packets_received,
                   &bytes_transmitted, &packets_transmitted) == 5) {
                    
                    stats_end->bytes_received = bytes_received;
                    stats_end->packets_received = packets_received;
                    stats_end->bytes_transmitted = bytes_transmitted;
                    stats_end->packets_transmitted = packets_transmitted;
                    break;
        }
    }

    fclose(file);

    unsigned long long net_in = stats_end->bytes_received - stats_start->bytes_received;
    unsigned long long net_out = stats_end->bytes_transmitted - stats_start->bytes_transmitted;

    double net_in_kb = net_in / 1024.0 / interval;
    double net_out_kb = net_out / 1024.0 / interval;

    printf("Network In: %.2f KiB/s Network Out: %.2f KiB/s\n", net_in_kb, net_out_kb);


    free(stats_start);
    free(stats_end);

    return 0;
}