// system_data.h
#ifndef SYSTEM_DATA_H
#define SYSTEM_DATA_H


// I would have never thought of using a struct to return multiple values from a function. <- generated by copilot, I only typed I wo...
struct NetworkUsage {
    double inbound;
    double outbound;
};

int cpu_data();
int memory_data();
int diskio_data();
double network_data(int interval, struct NetworkUsage* usage);

#endif // SYSTEM_DATA_H