#include "system_data.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/sysinfo.h>


int cpu_data() {
    FILE* file = fopen("/proc/stat", "r");
    if (file == NULL) {
        // Error handling
        return -1;
    }

    char line[256];
    fgets(line, sizeof(line), file);

    char* token = strtok(line, " ");
    int user = atoi(token);
    token = strtok(NULL, " ");
    int nice = atoi(token);
    token = strtok(NULL, " ");
    int system = atoi(token);
    token = strtok(NULL, " ");
    int idle = atoi(token);

    fclose(file);

    int total = user + nice + system + idle;
    double total_cpu_usage = 100.0 - (100.0 * idle / total);

    printf("CPU Usage: %.2f%%\n", total_cpu_usage);

    return 0;
}

int memory_data(){

    int MemTotal = 0, MemFree = 0, Buffers = 0, Cached = 0;

    FILE* file = fopen("/proc/meminfo", "r");
    if (file == NULL) {
        // Error handling
        return -1;
    }

    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file)) {
        if (sscanf(buffer, "MemTotal: %d kB", &MemTotal) == 1) {

        } else if (sscanf(buffer, "MemFree: %d kB", &MemFree) == 1) {

        } else if (sscanf(buffer, "Buffers: %d kB", &Buffers) == 1) {

        } else if (sscanf(buffer, "Cached: %d kB", &Cached) == 1) {

        }
    }
    fclose(file);
    
    int MemUsed = MemTotal - MemFree - Buffers - Cached;

    int MemUsedPercentage = 100 * MemUsed / MemTotal;

    printf("Memory Usage: %d%%\n", MemUsedPercentage);

    return 0;
       
}

// ! after making the other 2 funcs copilot knew exactly what I wanted to do next. Even this comment..... scary stuff.
// ! I'm not sure if I should be happy or scared. I'm happy that it's so smart but scared that it's so smart. <-this comment was also generated by copilot.
// ! anyway it got it wrong it wont copile life aint that easy.
int diskio_data(){
    const char* target_device = "sda";
    FILE* file = fopen("/proc/diskstats", "r");
    if (file == NULL) {
        // Error handling
        return -1;
    }


    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file)) {
        int major, minor;
        char device[256];
        unsigned long long reads, reads_merged, sectors_read, read_time;
        unsigned long long writes, writes_merged, sectors_written, write_time;
        unsigned long long io_in_progress, io_time, io_time_weighted;


        // ? added more specifiers that it needed?? bruh.
        // gave me what I wanted but not exactly. Some work to be done but 
        // definitely a good start.
        if (sscanf(buffer, "%d %d %s %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu",
                   &major, &minor, device,
                   &reads, &reads_merged, &sectors_read, &read_time,
                   &writes, &writes_merged, &sectors_written, &write_time,
                   &io_in_progress, &io_time, &io_time_weighted) >= 14) {
            if (strcmp(device, target_device) == 0) {
                unsigned long long total_io_ms = read_time + write_time;
                double total_io_seconds = total_io_ms / 1000.0;

                printf("Total I/O Wait Time: %.3f seconds\n", total_io_seconds);

                break;
            }
        }
    }

    fclose(file);
    return 0;
}